'use client';
import { Droppable,Draggable } from '@hello-pangea/dnd';
import type { Deal } from '@/types/deal.types';
import type { DealStage } from '@/types/api.types';
import { DealCard } from './DealCard';
import { formatCurrency } from '@/lib/utils';
const labels:Record<DealStage,string>={PROSPECTING:'Prospecting',NEGOTIATION:'Negotiation',SETTLEMENT:'Settlement',PAYMENT:'Payment',CLIENT_RETENTION:'Client Retention'};
const bars:Record<DealStage,string>={PROSPECTING:'bg-violet-500',NEGOTIATION:'bg-blue-500',SETTLEMENT:'bg-amber-500',PAYMENT:'bg-green-500',CLIENT_RETENTION:'bg-pink-500'};
export const PipelineColumn=({stage,deals,onOpen}:{stage:DealStage;deals:Deal[];onOpen:(deal:Deal)=>void})=><section className="min-w-[285px] flex-1"><div className="mb-3 rounded-xl border bg-white p-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${bars[stage]}`}/><h3 className="text-sm font-semibold">{labels[stage]}</h3><span className="rounded-full bg-muted px-2 text-xs">{deals.length}</span></div><strong className="text-xs">{formatCurrency(deals.reduce((total,deal)=>total+deal.value,0))}</strong></div></div><Droppable droppableId={stage}>{(provided,snapshot)=><div ref={provided.innerRef} {...provided.droppableProps} className={`min-h-[520px] space-y-3 rounded-xl p-2 transition ${snapshot.isDraggingOver?'bg-primary/15':'bg-white/45'}`}>{deals.map((deal,index)=><Draggable key={deal.id} draggableId={deal.id} index={index}>{(drag)=><div ref={drag.innerRef} {...drag.draggableProps} {...drag.dragHandleProps}><DealCard deal={deal} onClick={()=>onOpen(deal)}/></div>}</Draggable>)}{provided.placeholder}{deals.length===0&&<p className="rounded-xl border border-dashed bg-white/70 p-6 text-center text-xs text-muted-foreground">Drop a deal here</p>}</div>}</Droppable></section>;
